version: '3'
tasks:
  test:
    cmd: 'vendor/bin/phpunit --coverage-html coverage {{.CLI_ARGS}}'

  cs-fix:
    cmd: 'vendor/bin/php-cs-fixer fix --diff --verbose {{.CLI_ARGS}}'

  cs:
    cmds:
      - task: cs-fix
        vars:
          CLI_ARGS: "--dry-run {{.CLI_ARGS}}"

  rector-fix:
    cmd: 'vendor/bin/rector process {{.CLI_ARGS}}'

  rector:
    cmds:
      - task: rector-fix
        vars:
          CLI_ARGS: "--dry-run {{.CLI_ARGS}}"

  stan:
    cmd: 'vendor/bin/phpstan {{.CLI_ARGS}}'
