version: '3'
tasks:
  test:
    cmd: 'vendor/bin/phpunit --coverage-html coverage {{.CLI_ARGS}}'

  cs-fix:
    cmd: 'vendor/bin/php-cs-fixer fix --diff --verbose {{.CLI_ARGS}}'

  cs:
    cmds:
      - task: cs-fix
        vars:
          CLI_ARGS: "--dry-run {{.CLI_ARGS}}"

  rector-fix:
    cmd: 'vendor/bin/rector process {{.CLI_ARGS}}'

  rector:
    cmds:
      - task: rector-fix
        vars:
          CLI_ARGS: "--dry-run {{.CLI_ARGS}}"

  stan:
    cmd: 'vendor/bin/phpstan {{.CLI_ARGS}}'

  install:
    cmd: 'composer install {{.CLI_ARGS}}'
    sources:
      - composer.json
      - composer.lock
    generates:
      - vendor/autoload.php

  composer-normalize-fix:
    deps: [install]
    cmds:
      - 'composer bump {{.CLI_ARGS}}'
      - 'composer normalize --diff {{.CLI_ARGS}}'

  composer-normalize:
    cmds:
      - task: composer-normalize-fix
        vars:
          CLI_ARGS: '--dry-run {{.CLI_ARGS}}'

  composer-validate: '{{.PHP}} composer validate --strict --no-check-publish {{.CLI_ARGS}}'

  composer-audit: '{{.PHP}} composer audit {{.CLI_ARGS}}'
